### ISSUE TITLE
buildMulterFields - issue with allOf/anyOf/oneOf schemas

### ISSUE THREAD

**Issue by jy95** [byu-oit/openapi-enforcer-multer#5]
Hello,

I think I found a small bug with this [function](https://github.com/byu-oit/openapi-enforcer-multer/blob/master/index.js#L93) : Using allOf/anyOf/oneOf in schemas will ignore the endpoint, even if it is a multipart/formdata (and an object).

Here is my [specification for that endpoint](https://github.com/SourceCodeOER/sourcecode_api/blob/master/openapi/paths/create_exercise.yaml#L18)

![image](https://user-images.githubusercontent.com/9306961/71427653-26357980-26bb-11ea-8b0f-a7993a92112a.png)

Thanks in advanced @Gi60s 

EDIT: If you wish, you can reuse my [previous repo](https://github.com/jy95/demoBug) , copy the [path definition](https://github.com/SourceCodeOER/sourcecode_api/blob/master/openapi/paths/create_exercise.yaml#L18) ( no need for anything else as it reuses previous definitions from other issue ). You can create a dummy controller (like the previous one in the repo).

A small test : 

```js
it("Should be able to create an exercise with a file", async () => {
        const title = "MULTIPART FORM TESTING 1";
        const exercise_data = {
            "title": title,
            "description": "HELLO WORLD",
            "url": "https://inginious.info.ucl.ac.be/"
        };

        await request
            .post("/api/create_exercise")
            .set('Authorization', 'bearer ' + JWT_TOKEN)
            //.set('Content-Type', "multipart/form-data")
            .attach("exerciseFile", path.resolve(__dirname, "./file.zip"))
            .field(exercise_data)
            .field("tags[0][text]", "MULTI PART exercise")
            .field("tags[0][category_id]", 1)
            .expect(200);
});
```

**Comment by jy95** [comment]
Christmas gift : This piece of code should do the work in any case https://github.com/byu-oit/openapi-enforcer-multer/pull/6

**Comment by Gi60s** [comment]
I've been trying to catch up on Git issues and just got here. Has this issue been fixed with `openapi-enforcer-multer@0.1.3`? If so, I apologize that I did not see your fix until now.

**Comment by jy95** [comment]
No problem : as I said, even if they take time, answers are better than nothing ^^
Even with the last version, this issue was not fixed

**Comment by Gi60s** [comment]
Thanks for the PR. It's merged and published to NPM as version `0.1.4`.

**Comment by jy95** [comment]
You are welcome ;)

EDIT : I saw the conditional `req.files || []` was discarded https://github.com/byu-oit/openapi-enforcer-multer/commit/5286093511adfdedde962c5c2fc642de7efeacb7#r36589900 : not a typo ?
